# Generated by Django 3.1.1 on 2021-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://i.pinimg.com/originals/b6/9d/53/b69d53168ccb8e5daab6d5d460b773d8.jpg', max_length=1000),
        ),
    ]
